### ISSUE TITLE
A little help with CI and AWS

### ISSUE THREAD

**Issue by Greg767** [fcosrno/aws-sdk-php-codeigniter#1]
Hi,
Sorry for bothering you, but I've been searching for hours to get this right.
I am trying to install AWS in Codeiginiter.
I am not familiar with Composer, but I've followed the docs and I've installed it (I am on Win8 and using Netbeans, WAMP server).
So I have composer, the CI project is already up and running. I created a composer.json at the root as per your description in the readme, then what should I do? Shouldn't the json be in the third-party folder? How do I make it import the dependencies?

Thanks a lot
Greg

**Comment by fcosrno** [comment]
Hi Greg,

You're doing great! You just have one step left. After creating your composer.json file at the root you just have to run "composer install" from that same root folder. The json shoudl NOT be in the third-party folder. Don't do anything in there, composer takes care of everything in there like magic.

Read the "Using Composer" section in the Composer documentation: https://getcomposer.org/doc/00-intro.md#using-composer

**Comment by Greg767** [comment]
Thanks for your quick response! By the way I was missing the curl option enabled in wamp when I tried the first time, but after fixing that it installed everything correctly.
