### ISSUE TITLE
Using AWS S3 without Composer

### ISSUE THREAD

**Issue by cordonmedia** [fcosrno/aws-sdk-php-codeigniter#2]
I do not have composer. How can I start using S3 with CodeIgniter? I've put the AWS Folder with the S3 folder in the Libraries folder. I also put the files you provided into the locations specified. Anything else?

**Comment by fcosrno** [comment]
If you're not using Composer I guess you could try including the AWS SDK for PHP on "application/libraries/Aws_sdk.php". Notice on line 2 it is "using" the AWS SDK namespace, so you may have to autoload it in some other way. Composer simplifies all this so I highly recommend you install it via Composer. The SDK also recommends it: http://docs.aws.amazon.com/aws-sdk-php/guide/latest/installation.html#installation
