### ISSUE TITLE
Can't load library

### ISSUE THREAD

**Issue by mike131** [fcosrno/aws-sdk-php-codeigniter#3]
So I followed your steps and did the following.
1) Install aws_sdk via Composer
2) add Composer autoloader in the CodeIgniter's index.php in the root.
3) Add the config/aws_sdk.php with the correct keys
4) Add libraries/Aws_sdk 
5) Try to load the library in controller ($this->load->library('aws_sdk');)
6) Get a 500 error because it cannot load it....

I'm not sure what the problem is...

**Comment by mike131** [comment]
In my error_log, i see:
Class 'Aws\S3\S3Client' not found in /wdata/w_var/www/newrow_repo/demo/application/libraries/Aws_sdk.php on line 10

**Comment by mike131** [comment]
Ok, so I was able to resolve it by adding the require vendor/autoload.php to the top of the controller.

I am curious though if there is something I did wrong...

**Comment by fcosrno** [comment]
Hi Mike,

Yeah, it looks like you forgot to include vendor/autoload.php. I recommend you add it to your index.php instead the controller though. I usually add it right before the "LOAD THE BOOTSTRAP FILE" bit near the end of the Codeigniter index.php file.

**Comment by mike131** [comment]
I actually have that line in the index.php as well....

// Add autoload for composer installed packages
require_once './vendor/autoload.php';

This is right before the end of the index.php file

Edit:
It comes right after the line:
require_once BASEPATH.'core/CodeIgniter.php';

**Comment by fcosrno** [comment]
You might need to load vendor/autoload.php before core/CodeIgniter.php in the index.php file.

**Comment by mike131** [comment]
Will try that.

Thank you!
